FAQ (PDFNET-57969)
aspose-pdf/Aspose.PDF-Documentation pull request #299
Opened 2024-11-05 17:42 UTC by alevsh

2024-11-05 17:54 UTC, lightway82 commented
```
using (Document mergedDocuments = Document.MergeDocuments("input1.pdf", "input2.pdf", `"input3.pdf"))`
{
     mergedDocuments.Save(outputPdfFile);
 }
```

2024-11-05 18:06 UTC, AlexBiriukov reviewed
Some things need to be corrected.

2024-11-05 18:06 UTC, AlexBiriukov commented on net/faq/_index.md
> +To use regex with the `TextSegmentAbsorber` class in Aspose.PDF for .NET, you can follow this example:
Here and below: TextFragmentAbsorber, not TextSegmentAbsorber

2024-11-05 18:56 UTC, andruhovski requested changes

2024-11-05 18:56 UTC, andruhovski commented on net/faq/_index.md
> -<div class="schema-faq-code" itemscope="" itemtype="https://schema.org/FAQPage"><div itemscope="" itemprop="mainEntity" itemtype="https://schema.org/Question" class="faq-question"><h3 itemprop="name"
It's not an HTML code. It's a structured data entity FAQPage. Please restore!

2024-11-06 06:23 UTC, BaronRastignak reviewed
One more quite frequent PDF/A related question:

I see errors in a PDF/A conversion log. Does it mean that the document wasn't converted?

Answer: No, Aspose.PDF logs all problems it encountered, including the ones that were automatically fixed. If all entries in the log are marked as Convertable="True", it means that all problems were fixed, and the document was successfully converted. Only the entries with Convertable="False" indicate the conversion failure.

2024-11-06 06:23 UTC, BaronRastignak commented on net/faq/_index.md
> +## How to implement regex search for TextFragemntAbsorber?
Typo: TextFrag**me**ntAbsorber

2024-11-06 06:23 UTC, BaronRastignak commented on net/faq/_index.md
> +pdfDoc.FontUtilities.DefaultFontName = "Arial";
There is no such property here. The correct snippet may look like:
```csharp
using (Document pdfDoc = new Aspose.Pdf.Document("input.pdf"))
{
    PdfFormatConversionOptions options = new PdfFormatConversionOptions("conversion-log.xml", PdfFormat.PDF_A_1B, ConvertErrorAction.Delete);
    // Substitute all missing fonts with the default one
    options.FontEmbeddingOptions.UseDefaultSubstitution = true;

    // Convert to PDF/A
    pdfDoc.Convert(options);

    // Save as PDF/A
    pdfDoc.Save("output-pdfa.pdf");
}
```

2024-11-06 06:23 UTC, BaronRastignak commented on net/faq/_index.md
> +## Does Aspose.PDF for .NET support .NET 2.0, 3.5, and 4.0 frameworks?
We've dropped support for at least .NET Framework 2.0 and 3.5, haven't we?

2024-11-12 09:07 UTC, AnHolub approved these changes

2024-11-12 09:07 UTC, AnHolub commented on net/faq/_index.md
> +But you can use Aspose.PDF for .NET with any of these frameworks in your project. The library provides a consistent API across the different .NET versions, making it easy to migrate your code between
However, you can use Aspose.PDF for .NET with any of these frameworks for your project.

2024-11-12 09:07 UTC, AnHolub commented on net/faq/_index.md
> +No, Aspose.PDF logs all problems it encountered, including the ones that were automatically fixed. If all entries in the log are marked as Convertable="True", it means that all problems were fixed, a
If all entries in the log are marked as Convertable="True, " all problems were fixed, and the document was successfully converted. Only the entries with Convertable=False indicate the conversion failure.

2024-11-12 10:57 UTC, AlexBiriukov approved these changes
No new comments.

2024-11-14 08:18 UTC, merged